### ISSUE TITLE
Object none type issue

### ISSUE THREAD

**Issue by pattubaba** [mingkuan/voice-assistant-chatgpt#2]
File "C:\Users\FP391NN\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by mingkuan** [comment]
Can not reproduce the error. Please make sure to set your Python development environment correctly. Or you can run the docker image which had set the related Python environment for you. Try this command first: 

docker build -t voicebot-chatgpt -f Dockerfile .

And then run the docker image: 

docker run -it -p 8501:8501  --env-file  your.env.secrete.txt voicebot-chatgpt
